project_id = "wioxxtyaxfvgnexuslky"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[edge_runtime]
enabled = true
port = 54329

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.list-database-catalog]
verify_jwt = true

[functions.preview-table]
verify_jwt = true

[functions.test-rest-connection]
verify_jwt = true

[functions.ai-data-chat]
verify_jwt = true

[functions.ai-generate-insights]
verify_jwt = true

[functions.audit-log]
verify_jwt = true

[functions.superadmin-accounts]
verify_jwt = false

[functions.superadmin-suspend]
verify_jwt = false

[functions.superadmin-reactivate]
verify_jwt = false

[functions.superadmin-account-details]
verify_jwt = false

[functions.encrypt-password]
verify_jwt = true

[functions.decrypt-password]
verify_jwt = false

[functions.test-database-connection]
verify_jwt = true

[functions.create-connection]
verify_jwt = true

[functions.update-connection]
verify_jwt = true

[functions.delete-connection]
verify_jwt = true

[functions.run-sql-query]
verify_jwt = true

[functions.datasets-list]
verify_jwt = true

[functions.datasets-preview]
verify_jwt = true

[functions.datasets-create]
verify_jwt = true

[functions.charts-run]
verify_jwt = true