// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wioxxtyaxfvgnexuslky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indpb3h4dHlheGZ2Z25leHVzbGt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTU4OTAsImV4cCI6MjA2MjEzMTg5MH0.MBy2zyLPBfIqkbEIdpepd9HYt1TK22UzVU8MaHGMlK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});